name: Pre-release

permissions: read-all

on:
  push:
    branches:
      - release-please-*

jobs:
  pre-release:
    name: 'Verify MCP server schema unchanged'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: npm
          node-version-file: '.nvmrc'

      - name: Install MCP Publisher
        run: |
          export OS=$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
          curl -L "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_${OS}.tar.gz" | tar xz mcp-publisher

      - name: Verify server.json
        run: npm run verify-server-json-version
